# **Exemplo**

Analisar dados de consumidores de energia elétrica usando Python.

In [1]:
# Importar biblioteca de análise de dados ----> Pandas
import pandas as pd

In [2]:
# Carregar os dados criando uma tabela
tabela = pd.read_csv('/content/household_power_consumption.csv')

In [6]:
# Visualizar primeiros registros da tabela
tabela.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2008-01-12 00:00:00,2026-03-30 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-03-30 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-03-06 00:00:00,2026-03-30 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-09-05 00:00:00,2026-03-30 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-03-30 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [7]:
# Levantando estatísticas descritivas
tabela.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
count,204928.000000,204928.000000,204928.000000,204928.000000,204928.000000,204928.000000,204928.000000
mean,1.093172,0.124124,240.828559,4.634430,1.136463,1.317780,6.477397
std,1.063330,0.112645,3.245863,4.469326,6.200722,5.909236,8.452212
min,0.076000,0.000000,224.680000,0.200000,0.000000,0.000000,0.000000
25%,0.308000,0.048000,238.990000,1.400000,0.000000,0.000000,0.000000
50%,0.600000,0.100000,241.000000,2.600000,0.000000,0.000000,1.000000
75%,1.528000,0.196000,242.870000,6.400000,0.000000,1.000000,17.000000
max,10.536000,1.082000,253.750000,45.800000,83.000000,79.000000,31.000000

In [8]:
# Colunas
tabela.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [24]:
# Calculando a média aritmética de
# uma coluna Voltage (Tensão ----> em Volts)
# mean() ---> calcula média
# median() ---> calcula mediana
# std() ---> calcula desvio padrão
# round() ---> arredonda
media_tensao = tabela['Voltage'].mean()
mediana_tensao = tabela['Voltage'].median()
desvio_padrao_tensao = tabela['Voltage'].std()
# media_tensao, mediana_tensao, desvio_padrao_tensao
print(f'A média aritmética da coluna Voltage é {media_tensao:.3f}V')
print(f'A mediana da coluna Voltage é {mediana_tensao:.3f}V')
print(f'O desvio padrão da coluna Voltage é {desvio_padrao_tensao:.3f}V')

A média aritmética da coluna Voltage é 240.829V
A mediana da coluna Voltage é 241.000V
O desvio padrão da coluna Voltage é 3.246V

A média aritmética da coluna Voltage é 240.8V
A mediana da coluna Voltage é 241.0V
O desvio padrão da coluna Voltage é 3.2V

In [ ]:
# Amostra de 10% dos dados originais
tabela_amostra = tabela.sample(frac=0.1)

In [21]:
tabela.shape, tabela_amostra.shape

((204928, 9), (20493, 9))

In [25]:
# Dados da amostra
media_tensao_amostra = tabela_amostra['Voltage'].mean()
mediana_tensao_amostra = tabela_amostra['Voltage'].median()
desvio_padrao_tensao_amostra = tabela_amostra['Voltage'].std()
# media_tensao_amostra, mediana_tensao_amostra, desvio_padrao_tensao_amostra
print(f'A média aritmética da coluna Voltage é {media_tensao_amostra:.3f}V')
print(f'A mediana da coluna Voltage é {mediana_tensao_amostra:.3f}V')
print(f'O desvio padrão da coluna Voltage é {desvio_padrao_tensao_amostra:.3f}V')

A média aritmética da coluna Voltage é 240.793V
A mediana da coluna Voltage é 240.950V
O desvio padrão da coluna Voltage é 3.210V

In [ ]:
# Exercício (utilize a amostra):
# Calcular as métricas (média, mediana e desvio) da coluna Global_intensity

In [26]:
# Criar uma coluna com o cálculo do produto de tensão (Voltage) e corrente (Global_intensity)
tabela['Potencia_Aparente_1'] = tabela['Voltage'] * tabela['Global_intensity']
tabela.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Potencia_Aparente_1
0,2008-01-12 00:00:00,2026-03-30 09:44:00,1.502,0.074,240.17,6.4,0,0,18,1537.088
1,2006-12-17 00:00:00,2026-03-30 23:39:00,0.374,0.264,245.50,1.8,0,2,0,441.900
2,2009-03-06 00:00:00,2026-03-30 17:01:00,0.620,0.300,239.85,3.0,0,1,1,719.550
3,2007-09-05 00:00:00,2026-03-30 05:53:00,0.280,0.200,235.72,1.4,0,0,0,330.008
4,2008-12-14 00:00:00,2026-03-30 02:57:00,1.372,0.054,243.95,5.6,0,0,18,1366.120